doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types: 
            uuid: Ramsey\Uuid\Doctrine\UuidType
            GenderType: App\DBAL\Types\GenderType
            SexualOrientationType: App\DBAL\Types\SexualOrientationType
            StreamingPlatformType: App\DBAL\Types\StreamingPlatformType
            geography: Jsor\Doctrine\PostGIS\Types\GeographyType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
