services:
    Jsor\Doctrine\PostGIS\Event\ORMSchemaEventSubscriber:
        tags: [{ name: doctrine.event_subscriber, connection: default }]

doctrine:
    dbal:
        mapping_types:
            _text: string
        types:
            geometry: 'Jsor\Doctrine\PostGIS\Types\GeometryType'
    orm:
        dql:
            string_functions:
                ST_AsGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_AsGeoJSON'
                ST_GeomFromGeoJSON: 'Jsor\Doctrine\PostGIS\Functions\ST_GeomFromGeoJSON'
                ST_Distance: 'Jsor\Doctrine\PostGIS\Functions\ST_Distance'
                ST_GeographyFromText: 'Jsor\Doctrine\PostGIS\Functions\ST_GeographyFromText'
                ST_SetSRID: 'Jsor\Doctrine\PostGIS\Functions\ST_SetSRID'
                ST_Point: 'Jsor\Doctrine\PostGIS\Functions\ST_Point'
