#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /login
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path: /login/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
