# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    SpotifyClientID: '%env(OAUTH_SPOTIFY_CLIENT_ID)%'
    SpotifyClientSecret: '%env(OAUTH_SPOTIFY_CLIENT_SECRET)%'
    SpotifyClientRedirectUri: '%env(OAUTH_SPOTIFY_CLIENT_REDIRECT_URI)%'
    app.server_mail_address: '%env(SERVER_MAIL_ADDRESS)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $serverMailAddress: '%app.server_mail_address%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            # - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
    
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Decorator\TrackslistDecorator:
        decorates: 'api_platform.openapi.normalizer'
        arguments: ['@.inner']
        autoconfigure: false
    App\Decorator\TracklistUpdateDecorator:
        decorates: 'api_platform.openapi.normalizer'
        arguments: ['@.inner']
        autoconfigure: false
    App\Decorator\JwtDecorator:
        decorates: 'api_platform.openapi.normalizer'
        arguments: ['@.inner']
        autoconfigure: false
    App\Decorator\DeleteJojoDecorator:
        decorates: 'api_platform.openapi.normalizer'
        arguments: ['@.inner']
        autoconfigure: false
    App\Decorator\TokenRefreshDecorator:
        decorates: 'api_platform.openapi.normalizer'
        arguments: ['@.inner']
        autoconfigure: false
    App\Decorator\OpenApiFactory:
        decorates: 'api_platform.openapi.factory'
        arguments: ['@.inner']
    'App\Serializer\AdminContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\AdminContextBuilder.inner' ]
        autoconfigure: false
    'App\Serializer\OwnerContextBuilder':
        decorates: 'api_platform.serializer.context_builder'
        arguments: [ '@App\Serializer\OwnerContextBuilder.inner' ]
        autoconfigure: false
    Kerox\OAuth2\Client\Provider\Spotify:
        class: Kerox\OAuth2\Client\Provider\Spotify
        arguments:
            - {clientId: '%env(OAUTH_SPOTIFY_CLIENT_ID)%', clientSecret: '%env(OAUTH_SPOTIFY_CLIENT_SECRET)%', redirectUri: '%env(OAUTH_SPOTIFY_CLIENT_REDIRECT_URI)%'}
    League\OAuth2\Client\Provider\Github:
        class: League\OAuth2\Client\Provider\Github
        arguments:
            - {clientId: '%env(OAUTH_GITHUB_ID)%', clientSecret: '%env(OAUTH_GITHUB_SECRET)%'}
