api_platform:
    resource: .
    type: api_platform

authentication_token:
    path: /login
    methods: ['POST']

gesdinet_jwt_refresh_token:
    path: /login/refresh
    controller: gesdinet.jwtrefreshtoken::refresh
